[package]
name = "vacuum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.26.0"
sqlite3-sys = {version ="0.13.0", features=["linkage"]}
